import React, { useState, useEffect } from 'react';
import { X, Receipt, CreditCard, ChevronDown, Info } from 'lucide-react';
import { getAllAccountingCodes, type AccountingCode } from '../../../services/accountingService';
import { getAllTaxes, type Tax } from '../../../services/taxService';
import { createPayment, type CreatePaymentPayload, type PaymentMethod, type PaymentStatus } from '../../../services/paymentService';

interface PurchaseBillModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSuccess: () => void;
    poId: string;
    poNumber: string;
    totalAmount: number;
}

const PurchaseBillModal: React.FC<PurchaseBillModalProps> = ({
    isOpen,
    onClose,
    onSuccess,
    poId,
    poNumber,
    totalAmount
}) => {
    const [loading, setLoading] = useState(false);
    const [fetchingData, setFetchingData] = useState(true);
    const [accountingCodes, setAccountingCodes] = useState<AccountingCode[]>([]);
    const [taxes, setTaxes] = useState<Tax[]>([]);

    const [formData, setFormData] = useState({
        accountingCode: '',
        paymentMethod: 'BANK_TRANSFER' as PaymentMethod,
        isTaxInclusive: true,
        amount: totalAmount, // Initialized to PO total
        taxApplied: '',
        status: 'COMPLETED' as PaymentStatus,
        notes: `Payment for Purchase Order ${poNumber}`
    });

    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        if (isOpen) {
            fetchRequiredData();
            setFormData(prev => ({
                ...prev,
                amount: totalAmount,
                notes: `Payment for Purchase Order ${poNumber}`
            }));
        }
    }, [isOpen, totalAmount, poNumber]);

    const fetchRequiredData = async () => {
        setFetchingData(true);
        try {
            const [codes, taxList] = await Promise.all([
                getAllAccountingCodes(),
                getAllTaxes()
            ]);
            // Allow all accounting codes as generated by the admin
            setAccountingCodes(codes);
            setTaxes(taxList.filter(t => t.isActive));
        } catch (err) {
            console.error('Failed to fetch modal data:', err);
        } finally {
            setFetchingData(false);
        }
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        setError(null);

        try {
            const payload: CreatePaymentPayload = {
                accountingCode: formData.accountingCode,
                referenceId: poId,
                referenceModel: 'PurchaseOrder',
                transactionCategory: 'EXPENSE',
                transactionType: 'DEBIT',
                paymentMethod: formData.paymentMethod,
                isTaxInclusive: formData.isTaxInclusive,
                status: formData.status,
                notes: formData.notes
            };

            if (formData.isTaxInclusive) {
                payload.totalAmount = formData.amount;
            } else {
                payload.baseAmount = formData.amount;
            }

            if (formData.taxApplied) {
                payload.taxApplied = formData.taxApplied;
            }

            await createPayment(payload);
            onSuccess();
            onClose();
        } catch (err: any) {
            setError(err.response?.data?.message || err.message || 'Failed to register bill');
        } finally {
            setLoading(false);
        }
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-200">
            <div 
                className="w-full max-w-2xl bg-[var(--bg-card)] border border-[var(--border-main)] rounded-2xl overflow-hidden shadow-2xl animate-in zoom-in-95 duration-200 flex flex-col max-h-[90vh]"
                onClick={e => e.stopPropagation()}
            >
                {/* Header */}
                <div className="px-6 py-4 border-b border-[var(--border-main)] flex justify-between items-center bg-white/5">
                    <div className="flex items-center gap-3">
                        <div className="p-2 rounded-lg bg-[#C8E600]/10 text-[#C8E600]">
                            <Receipt size={24} />
                        </div>
                        <div>
                            <h3 className="text-xl font-bold" style={{ color: 'var(--text-main)' }}>Register Purchase Bill</h3>
                            <p className="text-xs" style={{ color: 'var(--text-dim)' }}>Reference: {poNumber}</p>
                        </div>
                    </div>
                    <button onClick={onClose} className="p-2 hover:bg-white/5 rounded-lg transition-colors" style={{ color: 'var(--text-dim)' }}>
                        <X size={20} />
                    </button>
                </div>

                {/* Form */}
                <form onSubmit={handleSubmit} className="p-6 space-y-6 overflow-y-auto">
                    {error && (
                        <div className="p-4 rounded-xl bg-red-500/10 border border-red-500/20 text-red-500 text-sm flex items-center gap-2">
                            <Info size={16} /> {error}
                        </div>
                    )}

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {/* Accounting Code */}
                        <div className="space-y-2">
                            <label className="text-xs font-bold uppercase tracking-wider" style={{ color: 'var(--text-dim)' }}>Accounting Code (GL Account)</label>
                            <div className="relative">
                                <select
                                    required
                                    value={formData.accountingCode}
                                    onChange={e => setFormData({ ...formData, accountingCode: e.target.value })}
                                    className="w-full px-4 py-3 rounded-xl bg-[var(--bg-input)] border border-[var(--border-main)] outline-none text-sm appearance-none focus:ring-2 focus:ring-[#C8E600]/50 transition-all font-bold"
                                    style={{ color: 'var(--text-main)' }}
                                >
                                    <option value="">Select Account...</option>
                                    {accountingCodes.map(code => (
                                        <option key={code._id} value={code._id}>{code.code} - {code.name} ({code.category})</option>
                                    ))}
                                </select>
                                <ChevronDown size={16} className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none opacity-50" />
                            </div>
                        </div>

                        {/* Payment Method */}
                        <div className="space-y-2">
                            <label className="text-xs font-bold uppercase tracking-wider" style={{ color: 'var(--text-dim)' }}>Payment Method</label>
                            <div className="relative">
                                <select
                                    required
                                    value={formData.paymentMethod}
                                    onChange={e => setFormData({ ...formData, paymentMethod: e.target.value as PaymentMethod })}
                                    className="w-full px-4 py-3 rounded-xl bg-[var(--bg-input)] border border-[var(--border-main)] outline-none text-sm appearance-none focus:ring-2 focus:ring-[#C8E600]/50 transition-all"
                                    style={{ color: 'var(--text-main)' }}
                                >
                                    <option value="BANK_TRANSFER">Bank Transfer</option>
                                    <option value="CASH">Cash</option>
                                    <option value="CREDIT_CARD">Credit Card</option>
                                    <option value="CHEQUE">Cheque</option>
                                    <option value="OTHER">Other</option>
                                </select>
                                <ChevronDown size={16} className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none opacity-50" />
                            </div>
                        </div>

                        {/* Amount */}
                        <div className="space-y-2">
                            <label className="text-xs font-bold uppercase tracking-wider" style={{ color: 'var(--text-dim)' }}>
                                {formData.isTaxInclusive ? 'Grand Total (Tax Inclusive)' : 'Base Amount (Tax Exclusive)'}
                            </label>
                            <div className="relative">
                                <span className="absolute left-4 top-1/2 -translate-y-1/2 font-bold opacity-50">$</span>
                                <input
                                    type="number"
                                    step="0.01"
                                    required
                                    value={formData.amount}
                                    onChange={e => setFormData({ ...formData, amount: parseFloat(e.target.value) })}
                                    className="w-full pl-9 pr-4 py-3 rounded-xl bg-[var(--bg-input)] border border-[var(--border-main)] outline-none text-sm focus:ring-2 focus:ring-[#C8E600]/50 transition-all font-bold"
                                    style={{ color: 'var(--text-main)' }}
                                />
                            </div>
                        </div>

                        {/* Tax Profile */}
                        <div className="space-y-2">
                            <label className="text-xs font-bold uppercase tracking-wider" style={{ color: 'var(--text-dim)' }}>Tax Profile (Optional)</label>
                            <div className="relative">
                                <select
                                    value={formData.taxApplied}
                                    onChange={e => setFormData({ ...formData, taxApplied: e.target.value })}
                                    className="w-full px-4 py-3 rounded-xl bg-[var(--bg-input)] border border-[var(--border-main)] outline-none text-sm appearance-none focus:ring-2 focus:ring-[#C8E600]/50 transition-all"
                                    style={{ color: 'var(--text-main)' }}
                                >
                                    <option value="">No Tax</option>
                                    {taxes.map(tax => (
                                        <option key={tax._id} value={tax._id}>{tax.name} ({tax.rate}%)</option>
                                    ))}
                                </select>
                                <ChevronDown size={16} className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none opacity-50" />
                            </div>
                        </div>

                        {/* Tax Toggle */}
                        <div className="flex items-center gap-3 p-4 rounded-xl border border-[var(--border-main)] bg-white/5">
                            <div className="flex-1">
                                <p className="text-sm font-bold" style={{ color: 'var(--text-main)' }}>Tax Inclusive Pricing</p>
                                <p className="text-[10px]" style={{ color: 'var(--text-dim)' }}>Toggle off if amount is before tax.</p>
                            </div>
                            <button
                                type="button"
                                onClick={() => setFormData({ ...formData, isTaxInclusive: !formData.isTaxInclusive })}
                                className={`w-12 h-6 rounded-full transition-colors relative ${formData.isTaxInclusive ? 'bg-[#C8E600]' : 'bg-white/10'}`}
                            >
                                <div className={`absolute top-1 w-4 h-4 rounded-full bg-white shadow transition-all ${formData.isTaxInclusive ? 'right-1' : 'left-1'}`} />
                            </button>
                        </div>

                        {/* Initial Status */}
                        <div className="space-y-2">
                            <label className="text-xs font-bold uppercase tracking-wider" style={{ color: 'var(--text-dim)' }}>Initial Status</label>
                            <div className="relative">
                                <select
                                    required
                                    value={formData.status}
                                    onChange={e => setFormData({ ...formData, status: e.target.value as PaymentStatus })}
                                    className="w-full px-4 py-3 rounded-xl bg-[var(--bg-input)] border border-[var(--border-main)] outline-none text-sm appearance-none focus:ring-2 focus:ring-[#C8E600]/50 transition-all"
                                    style={{ color: 'var(--text-main)' }}
                                >
                                    <option value="COMPLETED">COMPLETED (Recommended)</option>
                                    <option value="PENDING">PENDING (Waiting for Clearance)</option>
                                </select>
                                <ChevronDown size={16} className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none opacity-50" />
                            </div>
                        </div>
                    </div>

                    {/* Notes */}
                    <div className="space-y-2">
                        <label className="text-xs font-bold uppercase tracking-wider" style={{ color: 'var(--text-dim)' }}>Transaction Notes</label>
                        <textarea
                            value={formData.notes}
                            onChange={e => setFormData({ ...formData, notes: e.target.value })}
                            placeholder="Add payment details, reference numbers, etc."
                            className="w-full px-4 py-3 rounded-xl bg-[var(--bg-input)] border border-[var(--border-main)] outline-none text-sm focus:ring-2 focus:ring-[#C8E600]/50 transition-all min-h-[100px] resize-none"
                            style={{ color: 'var(--text-main)' }}
                        />
                    </div>

                    {/* Warning about Ledger */}
                    {formData.status === 'COMPLETED' && (
                        <div className="p-4 rounded-xl bg-[#C8E600]/5 border border-[#C8E600]/20 flex items-start gap-3">
                            <Info size={18} className="text-[#C8E600] shrink-0 mt-0.5" />
                            <p className="text-xs leading-relaxed" style={{ color: 'var(--text-dim)' }}>
                                <strong style={{ color: 'var(--text-main)' }}>Note:</strong> Marking as COMPLETED will automatically generate a financial ledger entry. This action cannot be undone once processed.
                            </p>
                        </div>
                    )}
                </form>

                {/* Footer */}
                <div className="px-6 py-4 border-t border-[var(--border-main)] bg-white/5 flex gap-3">
                    <button
                        type="button"
                        onClick={onClose}
                        className="flex-1 py-3 rounded-xl text-sm font-medium transition-all hover:bg-white/5 border border-[var(--border-main)]"
                        style={{ color: 'var(--text-dim)' }}
                        disabled={loading}
                    >
                        Cancel
                    </button>
                    <button
                        onClick={handleSubmit}
                        disabled={loading || fetchingData || !formData.accountingCode}
                        className="flex-1 py-3 rounded-xl text-sm font-bold transition-all shadow-lg hover:-translate-y-0.5 active:translate-y-0 flex items-center justify-center gap-2"
                        style={{ background: '#C8E600', color: '#0A0A0A' }}
                    >
                        {loading ? (
                            <div className="w-5 h-5 border-2 border-current border-t-transparent rounded-full animate-spin" />
                        ) : (
                            <>
                                <CreditCard size={18} /> Register Payment
                            </>
                        )}
                    </button>
                </div>
            </div>
        </div>
    );
};

export default PurchaseBillModal;
