import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { FileText, Edit, History, Plus, Search, Globe, Download } from 'lucide-react';
import agreementService from '../../services/agreementService';
import type { Agreement } from '../../services/agreementService';
import { useNavigate } from 'react-router-dom';
import { jsPDF } from 'jspdf';
import toast from 'react-hot-toast';

interface AgreementListProps {
    onViewHistory: (agreement: Agreement) => void;
}

const AgreementList = ({ onViewHistory }: AgreementListProps) => {
    const { t } = useTranslation();
    const navigate = useNavigate();
    const [agreements, setAgreements] = useState<Agreement[]>([]);
    const [loading, setLoading] = useState(true);
    const [countryFilter, setCountryFilter] = useState('');
    const [searchQuery, setSearchQuery] = useState('');

    const fetchAgreements = async () => {
        setLoading(true);
        try {
            const data = await agreementService.getAgreements({ country: countryFilter || undefined });
            setAgreements(data);
        } catch (error) {
            console.error('Failed to fetch agreements:', error);
        } finally {
            setLoading(false);
        }
    };

    const handleDownloadPDF = async (agreement: Agreement) => {
        const toastId = toast.loading(t('management.agreements.list.toast.generating'));
        try {
            const doc = new jsPDF({
                unit: 'pt',
                format: 'a4',
                orientation: 'portrait'
            });

            // Create a temporary container for rendering
            const container = document.createElement('div');
            container.style.width = '550pt'; // A4 width minus padding
            container.style.padding = '40pt';
            container.style.color = '#111';
            container.style.fontFamily = 'serif';
            container.style.lineHeight = '1.6';
            
            container.innerHTML = `
                <div style="border-bottom: 2pt solid #A3E635; padding-bottom: 10pt; margin-bottom: 20pt;">
                    <h1 style="font-size: 24pt; margin: 0; color: #111;">${agreement.title}</h1>
                    <p style="font-size: 10pt; color: #666; margin: 5pt 0 0 0;">
                        Country: ${agreement.country} | Version: ${agreement.version} | Date: ${new Date().toLocaleDateString()}
                    </p>
                </div>
                <div style="font-size: 11pt; color: #333;">
                    ${agreement.content}
                </div>
                <div style="margin-top: 40pt; padding-top: 10pt; border-top: 0.5pt solid #eee; font-size: 8pt; color: #999; text-align: center;">
                    Generated by Ola Cars Legal Management System
                </div>
            `;

            // Inject styles to handle common TipTap tags
            const style = document.createElement('style');
            style.innerHTML = `
                h1, h2, h3 { font-family: sans-serif; margin-top: 1.5em; margin-bottom: 0.5em; color: #111; }
                p { margin-bottom: 1em; }
                ul, ol { margin-bottom: 1em; padding-left: 2em; }
                li { margin-bottom: 0.5em; }
                blockquote { border-left: 3pt solid #A3E635; padding-left: 10pt; font-style: italic; color: #555; margin: 1em 0; }
                a { color: #A3E635; text-decoration: underline; }
                table { width: 100%; border-collapse: collapse; margin: 1em 0; }
                th, td { border: 1pt solid #eee; padding: 8pt; text-align: left; }
                th { background: #f9f9f9; }
                .has-text-align-left { text-align: left; }
                .has-text-align-center { text-align: center; }
                .has-text-align-right { text-align: right; }
                .has-text-align-justify { text-align: justify; }
                img { max-width: 100%; height: auto; display: block; margin: 10pt auto; border-radius: 4pt; }
            `;
            container.appendChild(style);
            document.body.appendChild(container);

            await doc.html(container, {
                x: 20,
                y: 20,
                width: 550,
                windowWidth: 800
            });

            doc.save(`${agreement.title.replace(/\s+/g, '_')}_v${agreement.version}.pdf`);
            toast.success(t('management.agreements.list.toast.success'), { id: toastId });
        } catch (error) {
            console.error('PDF generation failed:', error);
            toast.error(t('management.agreements.list.toast.failed'), { id: toastId });
        } finally {
            const container = document.querySelector('div[style*="550pt"]');
            if (container) document.body.removeChild(container);
        }
    };

    useEffect(() => {
        fetchAgreements();
    }, [countryFilter]);

    const filteredAgreements = agreements.filter(a => 
        a.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        a.type.toLowerCase().includes(searchQuery.toLowerCase())
    );

    const getStatusColor = (status: string) => {
        switch (status) {
            case 'PUBLISHED': return 'text-green-500 bg-green-500/10';
            case 'DRAFT': return 'text-yellow-500 bg-yellow-500/10';
            case 'ARCHIVED': return 'text-red-500 bg-red-500/10';
            default: return 'text-gray-500 bg-gray-500/10';
        }
    };

    return (
        <div className="space-y-6">
            {/* Toolbar */}
            <div className="flex flex-col md:flex-row gap-4 justify-between items-start md:items-center">
                <div className="flex flex-wrap gap-3 w-full md:w-auto">
                    <div className="relative flex-1 md:w-64">
                        <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-dim" size={18} />
                        <input
                            type="text"
                            placeholder={t('management.agreements.list.searchPlaceholder')}
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            className="w-full pl-10 pr-4 py-2.5 rounded-xl border outline-none focus:ring-2 focus:ring-lime transition-all"
                            style={{ background: 'var(--bg-input)', borderColor: 'var(--border-main)', color: 'var(--text-main)' }}
                        />
                    </div>
                    <div className="relative">
                        <Globe className="absolute left-3 top-1/2 -translate-y-1/2 text-dim" size={18} />
                        <select
                            value={countryFilter}
                            onChange={(e) => setCountryFilter(e.target.value)}
                            className="pl-10 pr-8 py-2.5 rounded-xl border outline-none focus:ring-2 focus:ring-lime transition-all appearance-none cursor-pointer"
                            style={{ background: 'var(--bg-input)', borderColor: 'var(--border-main)', color: 'var(--text-main)' }}
                        >
                            <option value="">{t('management.common.allCountries')}</option>
                            <option value="US">USA</option>
                            <option value="IN">India</option>
                            <option value="KE">Kenya</option>
                            <option value="NG">Nigeria</option>
                        </select>
                    </div>
                </div>

                <button
                    onClick={() => navigate('new')}
                    className="flex items-center gap-2 px-6 py-2.5 rounded-xl font-bold transition-all hover:scale-105 active:scale-95 whitespace-nowrap"
                    style={{ background: 'var(--brand-lime)', color: 'var(--brand-black)' }}
                >
                    <Plus size={20} /> {t('management.agreements.list.createBtn')}
                </button>
            </div>

            {/* Table */}
            <div className="rounded-2xl border overflow-hidden" style={{ background: 'var(--bg-card)', borderColor: 'var(--border-main)' }}>
                <div className="overflow-x-auto">
                    <table className="w-full text-left border-collapse">
                        <thead>
                            <tr style={{ background: 'rgba(255,255,255,0.02)' }}>
                                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-dim">{t('management.agreements.list.table.title')}</th>
                                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-dim">{t('management.agreements.list.table.country')}</th>
                                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-dim">{t('management.agreements.list.table.type')}</th>
                                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-dim">{t('management.agreements.list.table.version')}</th>
                                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-dim">{t('management.agreements.list.table.status')}</th>
                                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-dim">{t('management.agreements.list.table.lastUpdated')}</th>
                                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-dim text-right">{t('management.common.table.actions')}</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-white/5" style={{ borderColor: 'var(--border-main)' }}>
                            {loading ? (
                                Array(5).fill(0).map((_, i) => (
                                    <tr key={i} className="animate-pulse">
                                        <td colSpan={7} className="px-6 py-4">
                                            <div className="h-6 bg-white/5 rounded w-full"></div>
                                        </td>
                                    </tr>
                                ))
                            ) : filteredAgreements.length === 0 ? (
                                <tr>
                                    <td colSpan={7} className="px-6 py-12 text-center text-dim">
                                        {t('management.agreements.list.noAgreements')}
                                    </td>
                                </tr>
                            ) : (
                                filteredAgreements.map((agreement) => (
                                    <tr key={agreement._id} className="hover:bg-white/[0.02] transition-colors group">
                                        <td className="px-6 py-4">
                                            <div className="flex items-center gap-3">
                                                <div className="p-2 rounded-lg bg-lime/10 text-lime">
                                                    <FileText size={18} />
                                                </div>
                                                <span className="font-semibold text-main">{agreement.title}</span>
                                            </div>
                                        </td>
                                        <td className="px-6 py-4">
                                            <div className="flex items-center gap-2 text-sm text-main">
                                                <Globe size={14} className="text-dim" />
                                                {agreement.country}
                                            </div>
                                        </td>
                                        <td className="px-6 py-4">
                                            <span className="text-xs font-bold px-2 py-1 rounded bg-white/5 text-dim border border-white/10 uppercase">
                                                {agreement.type.replace(/_/g, ' ')}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4">
                                            <span className="text-sm font-mono text-lime bg-lime/10 px-2 py-0.5 rounded">
                                                v{agreement.version}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4">
                                            <span className={`text-[10px] font-bold px-2.5 py-1 rounded-full uppercase tracking-wider ${getStatusColor(agreement.status)}`}>
                                                {t(`management.agreements.statusLabels.${agreement.status}`)}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-sm text-dim">
                                            {new Date(agreement.updatedAt || agreement.createdAt).toLocaleDateString()}
                                        </td>
                                        <td className="px-6 py-4 text-right">
                                            <div className="flex justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                                                <button
                                                    onClick={() => navigate(`edit/${agreement._id}`)}
                                                    className="p-2 rounded-lg hover:bg-white/10 text-main transition-colors"
                                                    title={t('management.agreements.list.actions.edit')}
                                                >
                                                    <Edit size={18} />
                                                </button>
                                                <button
                                                    onClick={() => handleDownloadPDF(agreement)}
                                                    className="p-2 rounded-lg hover:bg-white/10 text-main transition-colors"
                                                    title={t('management.agreements.list.actions.download')}
                                                >
                                                    <Download size={18} />
                                                </button>
                                                <button
                                                    onClick={() => onViewHistory(agreement)}
                                                    className="p-2 rounded-lg hover:bg-white/10 text-main transition-colors"
                                                    title={t('management.agreements.list.actions.history')}
                                                >
                                                    <History size={18} />
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
};

export default AgreementList;
